name: CI/CD - Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_BACKEND: sikanderali/backend
      IMAGE_FRONTEND: sikanderali/frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      - name: Generate Version Tag
        id: version
        run: |
          echo "VERSION=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Build & Push Backend
      - name: Build Backend Image
        run: |
          docker build -t $IMAGE_BACKEND:${{ env.VERSION }} ./backend
          docker push $IMAGE_BACKEND:${{ env.VERSION }}

      # Build & Push Frontend
      - name: Build Frontend Image
        run: |
          docker build -t $IMAGE_FRONTEND:${{ env.VERSION }} ./frontend
          docker push $IMAGE_FRONTEND:${{ env.VERSION }}

      # Update Backend K8s Manifest
      - name: Update Backend Deployment
        run: |
          sed -i "s|image: .*/backend:.*|image: $IMAGE_BACKEND:${{ env.VERSION }}|g" manifest/backend/deployment.yaml

      # Update Frontend K8s Manifest
      - name: Update Frontend Deployment
        run: |
          sed -i "s|image: .*/frontend:.*|image: $IMAGE_FRONTEND:${{ env.VERSION }}|g" manifest/frontend/deployment.yaml

      # Commit changes to Git
      - name: Commit and Push Updated Manifests
        run: |
          git config --global user.email "sikanderalikumbhar1@gmail.com"
          git config --global user.name "SIKANDERKUMBHAR"
          git add manifest/backend/deployment.yaml manifest/frontend/deployment.yaml
          git commit -m "Update manifests with version ${{ env.VERSION }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/SIKANDERKUMBHAR/genai-project-argocd.git
          git push origin main